import { useParams } from 'react-router-dom';
import { Link } from 'react-router-dom';
import Header from '../components/Header';
import Footer from '../components/Footer';

const Article = () => {
  const { id } = useParams();
  
  const articles = [
    {
      id: '1',
      title: "How to Use Reforestation Projects to Offset Your Carbon Footprint",
      content: `
        <p>Reforestation is one of the most effective natural solutions to climate change. Trees absorb carbon dioxide as they grow, storing carbon in their biomass.</p>
        <p>By participating in reforestation projects, you can:</p>
        <ul>
          <li>Offset your personal or business carbon emissions</li>
          <li>Support biodiversity and ecosystem restoration</li>
          <li>Contribute to sustainable community development</li>
        </ul>
        <h3>How to Get Started</h3>
        <p>Many organizations offer verified carbon offset programs through reforestation. Look for projects certified by standards like:</p>
        <ul>
          <li>Verified Carbon Standard (VCS)</li>
          <li>Gold Standard</li>
          <li>Climate Action Reserve</li>
        </ul>
      `,
      category: "Carbon Offsetting",
      date: "May 15, 2023"
    },
    {
      id: '2',
      title: "10 Simple Ways to Reduce Your Carbon Footprint at Home",
      content: `
        <p>Reducing your household carbon footprint can be easier than you think. Here are 10 simple changes that make a big difference:</p>
        <ol>
          <li><strong>Switch to LED light bulbs</strong> - Uses 75% less energy than incandescent bulbs</li>
          <li><strong>Lower your thermostat</strong> - Just 1-2 degrees in winter can save energy</li>
          <li><strong>Unplug electronics</strong> - "Vampire power" adds up even when devices are off</li>
          <li><strong>Wash clothes in cold water</strong> - 90% of a washing machine's energy heats water</li>
          <li><strong>Reduce meat consumption</strong> - Especially beef, which has high emissions</li>
        </ol>
      `,
      category: "Lifestyle",
      date: "April 28, 2023"
    },
    {
      id: '3',
      title: "Understanding Your Carbon Footprint: What It Is and Why It Matters",
      content: `
        <h3>What is a Carbon Footprint?</h3>
        <p>A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.</p>
        
        <h3>The Numbers</h3>
        <ul>
          <li>The average carbon footprint for a person in the United States is 16 tons</li>
          <li>Globally, the average is closer to 4 tons</li>
          <li>To avoid a 2℃ rise in global temperatures, we need to reach under 2 tons by 2050</li>
        </ul>
      `,
      category: "Education",
      date: "March 10, 2023"
    }
  ];
  
  const article = articles.find(a => a.id === id);

  if (!article) {
    return (
      <>
        <Header />
        <main className="article-page" style={{backgroundColor:"#87efe1ff"}}>
          <div className="container">
            <h1>Article not found</h1>
            <Link to="/resources" className="back-link">« Back to Resources</Link>
          </div>
        </main>
        <Footer />
      </>
    );
  }

  return (
    <>
      <Header />
      <main className="article-page">
        <div className="container">
          <div className="article-header">
            <span className="category">{article.category}</span>
            <span className="date">{article.date}</span>
          </div>
          <h1>{article.title}</h1>
          <div className="article-content" dangerouslySetInnerHTML={{ __html: article.content }} />
          <Link to="/resources" className="back-link">« Back to Resources</Link>
        </div>
      </main>
      <Footer />
    </>
  );
};

export default Article;